spring:
  profiles:
    include: oauth

  session:
    store-type: jdbc

  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true

  output:
    ansi:
      enabled: always

server:
  servlet:
    encoding:
      force: true
