spring:
  datasource:
    url: jdbc:h2:mem:db;MODE=MySQL;
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
  output:
    ansi:
      enabled: always